core:
  port: 8080
  local: localhost
  colony: False
  cmd_charset: GBK
  enWeb: True # True 启用Web界面 index.html于/resources/static，False为REST API

mcServer:
#  指定到resources下文件夹
  version: 1.9.4
  port: 23356
  def_cmd: cmd